### ISSUE TITLE
Support HAProxy's PROXY protocol for SMTP and IMAP

### ISSUE THREAD

**Issue by foxcpp** [foxcpp/maddy#369]
## Use case

Putting maddy behind a reverse proxy/load balancer/TLS terminator while still
providing necessary information for any policy validation.

## Implementation

See #296 for relevant discussion.

Exact configuration syntax and semantics is up for discussion.

## Task list

- [x] https://github.com/emersion/go-smtp/issues/147
- [x] https://github.com/emersion/go-smtp/pull/148
- [ ] Implement server support in endpoint/smtp
- [ ] Implement server support in endpoint/imap
- [ ] Implement client support in target.smtp (note that it would prevent pooling from working)

**Comment by foxcpp** [comment]
Use-cases to evaluate:

## maddy behind a TLS terminator for all endpoints

TLS terminator needs to be protocol aware for server-server SMTP: It needs to proxy SMTP capabilities and inject STARTTLS support, implement it and pass through all necessary metadata (EHLO hostname). maddy needs to be aware of TLS being used for security policy evaluation.

For client-server SMTP and IMAP any special support in TLS terminator is not needed as long as implicit TLS is used which is recommended by IETF over STARTTLS anyway.

In addition, it might be useful to support TLS between proxy and maddy. We can probably limit this to implicit TLS to keep things simple.

## TCP load balancer with TLS handled by maddy

Simplest configuration to be supported.

**Comment by foxcpp** [comment]
```
smtp tcp://127.0.0.1:2525 {
  proxy_protocol {
    assume_tls # should be turned on by default?
  }

  # if TLS is configured - it is for TLS between proxy and maddy. Not considered in policy evaluation.
  #tls ...

  ...
}

submission tcp://127.0.0.1:565 {
  proxy_protocol
  # insecure_auth assumed if proxy_protocol is used
}

imap tcp://127.0.0.1:1447 {
  proxy_protocol
  # insecure_auth assumed if proxy_protocol is used 
}
```

**Comment by foxcpp** [comment]
Blocked by https://github.com/emersion/go-smtp/issues/147

**Comment by infogulch** [comment]
This block seems to be resolved in https://github.com/emersion/go-smtp/pull/148

**Comment by infogulch** [comment]
It looks like Caddy 2 currently supports the PROXY protocol via the [caddy-l4](https://github.com/mholt/caddy-l4j) app (see linked discussion). So Caddy is in good company with other proxies that will support this mail reverse-proxy configuration.

From OP:

> Putting maddy behind a reverse proxy/load balancer/TLS terminator *while still providing necessary information for any policy validation*.

From README.md:

> In addition to that it implements auxiliary protocols that are mandatory to keep email reasonably secure (DKIM, SPF, DMARC, DANE, MTA-STS).

Will a plain PROXY-based reverse proxy still allow maddy to serve all of these these auxiliary protocols?

- [ ] [DKIM](https://en.wikipedia.org/wiki/DomainKeys_Identified_Mail) adds a signature to sent emails, and requires setting the signature public key in DNS.
- [x] [SPF](https://en.wikipedia.org/wiki/Sender_Policy_Framework) publishes which IP addresses are authorized to send email for a particular domain
- [x] [DMARC](https://en.wikipedia.org/wiki/DMARC) is a combined validation policy published in DNS TXT records that tells recipient infra how to validate DKIM/SPF for email received from a domain
- [x] [DANE](https://en.wikipedia.org/wiki/DNS-based_Authentication_of_Named_Entities) publishes DNS records that control which CAs are allowed to sign SMTP over TLS certificates, and its presence means TLS is required
- [ ] [MTA-STS](https://www.rfc-editor.org/rfc/rfc8461.html) is the complement to DANE, in that it publishes an https document (presumably authenticated by some public CA) that contains a policy indicating which DNS entries should be considered

Of these, only MTA-STS seems like it would need to be handled directly by the upstream proxy/Caddy. The rest come down to DNS configuration. Maybe there's an opportunity for a Caddy app that autoconfigures the necessary DNS (and either setting up DKIM manually, or pushing it out to be handled by caddy directly, see also [dkim-milter](https://github.com/emersion/go-msgauth/blob/master/cmd/dkim-milter/main.go), [maddy/internal/modify/dkim/keys.go](https://github.com/foxcpp/maddy/blob/master/internal/modify/dkim/keys.go), and ["/dkim.go](https://github.com/foxcpp/maddy/blob/master/internal/modify/dkim/dkim.go)).

See also [maddy's initial configuration docs](https://maddy.email/tutorials/setting-up/#dns-records).

**Comment by tomfitzhenry** [comment]
Looks like this was implemented in https://github.com/foxcpp/maddy/pull/568 ?

**Comment by reind33r** [comment]
Hello!

I have tried to use proxy_protocol for IMAP and submission, without success.

I am using HAProxy in TCP mode, and have tried with both `send-proxy` and `send-proxy-v2`.

Using Thunderbird to "debug" (trying both TLS and STARTTLS):

```
imap tls://0.0.0.0:993 tcp://0.0.0.0:143 {
    proxy_protocol 10.0.100.1
    debug yes

    ...
}
```

```
Jun 14 01:21:25 norrsken maddy[2165006]: [debug] imap: Trusted connection
Jun 14 01:21:25 norrsken maddy[2165006]: [debug] imap: Addresses len: 12
Jun 14 01:21:25 norrsken maddy[2165006]: [debug] imap: Address readed: 12
Jun 14 01:21:25 norrsken maddy[2165006]: [debug] imap: Use header remote addr
Jun 14 01:21:25 norrsken maddy[2165006]: [debug] imap: Header parsed &{1.2.3.4:52593 5.6.7.8:143}
Jun 14 01:25:31 norrsken maddy[2188640]: [debug] imap: Trusted connection
Jun 14 01:25:31 norrsken maddy[2188640]: [debug] imap: Read text signature error: tls: first record does not look like a TLS handshake
Jun 14 01:25:31 norrsken maddy[2188640]: [debug] imap: Parse header error: tls: first record does not look like a TLS handshake
Jun 14 01:25:31 norrsken maddy[2188640]: [debug] imap: Header parse error: tls: first record does not look like a TLS handshake
```

It looks like the PROXY headers are parsed correctly for STARTTLS, but then nothing happens. For the TLS port, it looks like maddy expects TLS [ ... ] but since HAProxy is just configured in TCP mode, it's receiving PROXY [ TLS [ ... ] ].

I thought that was the default usecase.

Is there something fishy in my configuration, or my understanding of the PROXY protocol?

I forward HTTP(S) traffic in a similar way to caddy without issues.
